### ISSUE TITLE
你好，gulp-seajs-transport 怎么使用必须的是js 文件吗？

### ISSUE THREAD

**Issue by linko2o** [guilipan/gulp-seajs-transport#12]
我在项目中用到handlebars

gulp.task('default' , function(){
    gulp.src('scripts/**/*.handlebars')
        .pipe(transport())
     .pipe(seaconcat(/\/src\//g))
     .pipe(uglify())
        .pipe(gulp.dest("dist/"));
})

出现以下错误，求指点

/home/faqian/workspace/yiyigu/node_modules/gulp-seajs-transport/node_modules/cmd-util/node_modules/uglify-js/lib/parse.js:204
    throw new JS_Parse_Error(message, line, col, pos);
          ^
Error
    at new JS_Parse_Error (/home/faqian/workspace/yiyigu/node_modules/gulp-seajs-transport/node_modules/cmd-util/node_modules/uglify-js/lib/parse.js:196:18)
    at js_error (/home/faqian/workspace/yiyigu/node_modules/gulp-seajs-transport/node_modules/cmd-util/node_modules/uglify-js/lib/parse.js:204:11)
    at croak (/home/faqian/workspace/yiyigu/node_modules/gulp-seajs-transport/node_modules/cmd-util/node_modules/uglify-js/lib/parse.js:636:9)
    at token_error (/home/faqian/workspace/yiyigu/node_modules/gulp-seajs-transport/node_modules/cmd-util/node_modules/uglify-js/lib/parse.js:644:9)
    at unexpected (/home/faqian/workspace/yiyigu/node_modules/gulp-seajs-transport/node_modules/cmd-util/node_modules/uglify-js/lib/parse.js:650:9)
    at expr_atom (/home/faqian/workspace/yiyigu/node_modules/gulp-seajs-transport/node_modules/cmd-util/node_modules/uglify-js/lib/parse.js:1131:9)
    at maybe_unary (/home/faqian/workspace/yiyigu/node_modules/gulp-seajs-transport/node_modules/cmd-util/node_modules/uglify-js/lib/parse.js:1287:19)
    at expr_ops (/home/faqian/workspace/yiyigu/node_modules/gulp-seajs-transport/node_modules/cmd-util/node_modules/uglify-js/lib/parse.js:1322:24)
    at maybe_conditional (/home/faqian/workspace/yiyigu/node_modules/gulp-seajs-transport/node_modules/cmd-util/node_modules/uglify-js/lib/parse.js:1327:20)
    at maybe_assign (/home/faqian/workspace/yiyigu/node_modules/gulp-seajs-transport/node_modules/cmd-util/node_modules/uglify-js/lib/parse.js:1351:20)

**Comment by guilipan** [comment]
对的，必须是js文件

**Comment by linko2o** [comment]
请问怎么使用.handlebars,.tpl结尾的文件呢

**Comment by guilipan** [comment]
模板文件不属于js模块，不需要进行seajs的transport的操作啊

**Comment by linko2o** [comment]
我想把一个模块的文件concat 成一个文件，让.handlebars,.tpl结尾的文件 也包含进出

**Comment by guilipan** [comment]
那我建议你用工具把tpl的模板编译成seajs的模块,暂时我不知道有没这样的工具,不过对于你的需求本插件还没办法做到

**Comment by mailylqj** [comment]
有什么办法可以让gulp-seajs-transport的爆错更友好一些，stream-combiner2感觉对gulp-seajs-transport没得作用！

**Comment by guilipan** [comment]
@mailylqj 随着ES6的普及，seajs用来打包的时代可能要进入尾声了，因此我可能也不打算对本插件进行长期维护了，建议你可以是用新的打包工具来实现模块化，如webpack2，fis3等工具
